### ISSUE TITLE
Source dist for package managers

### ISSUE THREAD

**Issue by outpaddling** [hwm2746/brain-mesh-builder#4]
Hi again...
It would be good if you could create a standard minimal source dist tag/release, with no object files, executables, or test output (unless it's needed for comparison), etc.  As of now I have a hack in the FreeBSD port and pkgsrc package to remove the Ubuntu binaries after extracting the dist and I'm not sure of the test output is useful, while it makes the dist tarball rather big.
Minor FYI, prefixing the release version with "v." or anything else is a minor nuisance for package managers.  A standard Github tag/release with a version of just x.y.z works with the defaults.
Thanks...

**Comment by acchangg12** [comment]
I made a new tag (1.1) without test folder and object files. Since github doesn't like empty folders, the ./bin/ and ./obj/ folders are gone, so a user would have to manually add these in to build.

**Comment by outpaddling** [comment]
That's great, thanks.  FYI, when you added the Makefile patches, the TABs got converted to spaces and things got out of alignment.  I'm attaching a fixed Makefile that also creates the bin and obj dirs automatically.
[Makefile.gz](https://github.com/hwm2746/brain-mesh-builder/files/9995542/Makefile.gz)

BTW, there's no rush to put out new releases on my account.  The FreeBSD ports and pkgsrc frameworks can work with a commit hash until everything is fully tested and you're ready for another release.

**Comment by acchangg12** [comment]
Thanks for catching that and for the updated Makefile - I went ahead and made the bug fix and updated Makefile. 

Great - glad to hear everything is working.
